QuestChronicle={version="1.9.0.7",Wardrobe={_Private={}},Diagnostics={_Private={}}}
local QC,W,WP,D,DP=QuestChronicle,QuestChronicle.Wardrobe,QuestChronicle.Wardrobe._Private,QuestChronicle.Diagnostics,QuestChronicle.Diagnostics._Private
WP.SUPPORT_SLOT_ORDER={"WAIST","HANDS","FEET","HEAD","BACK","WRIST","SHIRT","TABARD"}
W.GetSlotDefinition=function(key) return {key=key,label=key} end
D.GetHistoryCounters=function() return {reportsRecorded=10,duplicateInsertionsIgnored=0,malformedReportsDiscarded=0} end
local decisions={}
for index,slot in ipairs(WP.SUPPORT_SLOT_ORDER) do decisions[#decisions+1]={slotKey=slot,slotLabel=slot,name=string.rep(slot.." Appearance ",3),sourceID=1000+index,visualID=2000+index,itemID=3000+index,role="Contextual bridge and continuity role",profileFit=.812,neighborCohesion=.784,bridgeBonus=5.25,bridgeTarget="Chest ↔ Legs",bridgeBefore=.51,bridgeAfter=.73,mismatchSpent=.74,budgetState="WITHIN",outlierState="NORMAL",repeatPenalty=0,score=42.5} end
local report={version="1.9.0.7",timestamp=1,timestampText="2026-08-03 07:00:00",action="GENERATE_OUTFIT",mode="TRAVELER",result="COMPLETED",message=string.rep("Contextual support validation message. ",8),character={name="Tester",realm="Realm",className="WARRIOR"},context={profileLabel="Outland",eraLabel="The Burning Crusade"},outfit={generatedName="Contextual Test"},skeleton={chosenRank=1,shortlistSize=4,baseSkeletonScore=145.2,score=145.2,adjustedSelectionScore=130.2,repeatPenalty=-15,meanPairCohesion=.68,hardClashes=0,noveltyClass="MEANINGFULLY_NEW",comparedComponents={"Chest","Legs","Shoulders","Weapon bundle"},changedComponents={"Legs","Weapon bundle"},repeatedComponents={"Chest","Shoulders"},excludedComponents={},components={}},support={profile={activeAnchorCount=4,meanAnchorCohesion=.68,activeAnchors={{label="Chest"},{label="Legs"},{label="Shoulders"},{label="Weapon bundle"}},centers={palette="steel",material="plate",finish="military",motif="frontier",visualWeight=2.5,provenance=1},tolerance={palette=.1,material=.1,finish=.2,visualWeight=.2,motif=.2,provenance=.2},confidence={palette=.9,material=.9,finish=.9,visualWeight=.9,motifs=.9,provenance=.9},weakestRelationship={left="Chest",right="Weapon bundle",score=.55}},startingBudget=10.75,lockedCommitment=0,generatedSpend=5.92,borrowed=.2,overrun=0,remainingBudget=4.83,configurationScore=318.5,wholeOutfitCohesion=.79,controlledAccents=1,outliers=0,fallbackSlots=0,emptySlots=0,chosenRank=2,shortlistSize=6,poolSizes={},expansions={},retained={},deduplicated=12,budgetRejections=4,decisions=decisions,excluded={}},beam={poolSizes={},expansions={},retained={},weaponBundles=4,pairCacheHits=1000,pairCacheMisses=100,completeSkeletons=4,finalShortlist=4,chosenRank=1,weightedWindow=28,deduplicated=0,hardConstraintRejections=0,hardClashRejections=0},performance={steps=200,elapsedMs=2200,longestWorkerSliceMs=7.5,largestInstrumentedCallPhase="supportBeamExpansion",largestInstrumentedCallMs=1.5,candidates=4000,eraCandidates=0,selectedArmor=10,phaseStats={supportBeamExpansion={calls=500,totalMs=80,maxMs=1.5}}},cache={invalidationReasons={}},warnings={},comparison={changed={},unchanged={},excluded={},supportChanged=WP.SUPPORT_SLOT_ORDER,supportUnchanged={},supportExcluded={},previousMismatch=5,mismatch=5.92,previousWholeOutfitCohesion=.75,wholeOutfitCohesion=.79,previousOutliers=1,outliers=0}}
for _,slot in ipairs(WP.SUPPORT_SLOT_ORDER) do report.support.poolSizes[slot]=32; report.support.expansions[slot]=768; report.support.retained[slot]=24 end
dofile("Core/Diagnostics/SupportReportFormatter.lua")
dofile("Core/Diagnostics/ReportFormatter.lua")
local text=D.FormatCopyReport(report,true,true)
assert(text:find("Contextual Support",1,true) and text:find("Support changed",1,true),"complete Phase C report missing")
assert(#text < 20000,"formatted Phase C report exceeds 20 KB: "..#text)
print(string.format("PASS contextual support report size: %d decisions, %d bytes",#decisions,#text))
